// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7O-9avZJ1N2uXPWnDlcWMbSFwj2nDO34',
    appId: '1:676678541916:web:a39566188433ef8715fc99',
    messagingSenderId: '676678541916',
    projectId: 'fir-c0ncept',
    authDomain: 'fir-c0ncept.firebaseapp.com',
    storageBucket: 'fir-c0ncept.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB66sLlhTIVfQerrnyGcFSnz9tz_H6XOhE',
    appId: '1:676678541916:ios:8fe8ba4e0a7f9f6815fc99',
    messagingSenderId: '676678541916',
    projectId: 'fir-c0ncept',
    storageBucket: 'fir-c0ncept.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConcept',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7O-9avZJ1N2uXPWnDlcWMbSFwj2nDO34',
    appId: '1:676678541916:web:503be62208b2175315fc99',
    messagingSenderId: '676678541916',
    projectId: 'fir-c0ncept',
    authDomain: 'fir-c0ncept.firebaseapp.com',
    storageBucket: 'fir-c0ncept.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB66sLlhTIVfQerrnyGcFSnz9tz_H6XOhE',
    appId: '1:676678541916:ios:8fe8ba4e0a7f9f6815fc99',
    messagingSenderId: '676678541916',
    projectId: 'fir-c0ncept',
    storageBucket: 'fir-c0ncept.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConcept',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiK6CtAQsMuf94xrUmAQgQGTkKlnWfFrA',
    appId: '1:676678541916:android:2e896762a07e893a15fc99',
    messagingSenderId: '676678541916',
    projectId: 'fir-c0ncept',
    storageBucket: 'fir-c0ncept.firebasestorage.app',
  );

}